[build]
builder = "nixpacks"

[deploy]
startCommand = "node railway-server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production" 