[build]
builder = "nixpacks"

[deploy]
startCommand = "node railway-server.js"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.envs]
NODE_ENV = "production" 